version: "3.3"
services:
  redis:
    image: redis:6.0.7
    container_name: redis_chat
    restart: always
    volumes:
      - redis_volume_data:/data_chat
    ports:
      - 6369:6379
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight_chat
    restart: always
    ports:
      - 8011:8001
    volumes:
      - redis_insight_volume_data:/db_chat

volumes:
  redis_volume_data:
  redis_insight_volume_data: